public_network : "192.168.33.185"
hostname : "vagrant-php-web-dev"
hostsupdater : false
dependencies:
  php-71: false
  php-72: true
  php-73: false
  mysql : true
  sqlite : true
  java-8 : false
  mongodb : false
  nginx: false
  nodejs : true
  redis : false
  elasticsearch : false
database: "dev"
home_dir_folder: "www"